version: '3'
services:
  flask:
    build: .
    container_name: flask
    stop_signal: SIGINT
    ports:
      - '5001:5001'
    volumes:
      - .:/webapp
    depends_on:
      - redis
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest 
    container_name: mongodb
    ports:
      - "27017:27017"