version: '3'
services:
  flask:
    build: .
    container_name: flask
    stop_signal: SIGINT
    ports:
      - '5001:5001'
    volumes:
      - ./webapp:/webapp
    depends_on:
      - redis
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest 
    container_name: mongodb
    ports:
      - "27017:27017"
  neo4j:
    image: 'neo4j:latest'
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: 'neo4j/adminpass'
    healthcheck:
      test: cypher-shell --username neo4j --password adminpass 'MATCH (n) RETURN COUNT(n);'
      interval: 10s
      timeout: 10s
      retries: 5